samba-in-kubernetes/sit-test-cases

pyproject.toml

Having multiple packages layout requires explicit 'py-modules' entry for setuptools in order to avoid failures due to "Multiple top-level packages discovered in a flat-layout".

pyproject: add 'py-modules' entry for 'setuptools'

---

testcases/smbtorture/selftest/flapping.gluster

These tests  are being investigated at
https://github.com/gluster/samba-integration/issues/241
and it appears that these are caused by a bug in glusterfs.

smbtorture: add failing samba3.smb2.deny.* tests to flapping tests

---

testcases/consistency/test_consistency.py
testcases/mount/test_mount.py
testcases/smbtorture/test_smbtorture.py
testhelper/cmdhelper.py
testhelper/fshelper.py
testhelper/testhelper.py

Allow mypy to make better static type checking by using explicit type hints. 
In order to simplify review, this PR is split into sub-topics but the logic is pretty much the same all over: whenever possible, add explicit type-hints to function arguments and return type to allow mypy (via `make check-mypy` rule) to perform its static code checks. In addition, it also improves code readability.

mypy type hints

---

testcases/smbtorture/test_smbtorture.py

This is a clean up of the smbtorture test script. 
To run out smbtorture tests, we need to execute smbtorture and pipe it through the filter-subunit and format-subunit commands to return test results. The resulting command string generated is unwieldy.
We clean up the smbtorture tests by using the python subprocess module to pipe the output of each individual command and hopefully make it easier to maintain.

smbtorture: Use python subprocess module to execute each command

---

.github/workflows/ci.yaml
tox.ini

This change ensures that we focus to stay compatible with three most recent python versions and helps in making the codebase more robust.

CI: Enable testing with multiple python versions

---

testcases/mount/mount_io.py
testcases/mount/test_mount.py

Add extra I/O checks to mounted SMB share, using different files sizes and number-of-file per directory:
- Write-read + data consistency check.
- Overwrite-read + data consistency check.
- Stat + size check
- Unlink
Using Pyhton's pathlib over local mount-point.

mount: test I/O sanity

---

testcases/mount/mount_dbm.py
testcases/mount/test_mount.py

Use Python's standard dbm module to mimic and check minimal key-value
database I/O patterns. Uses both sequential and random insert and lookup
patterns. This test is intended to serve as minimal smoke-test before
testing FS+SMB with more complex (SQL) databases.
depends on #15

mount: check I/O with database workload

---

testcases/smbtorture/smbtorture-tests-info.yml

These tests are not best testing the samba protocol but they are
tweaks around some possible bug in windows which is not yet resolved:
https://lists.samba.org/archive/cifs-protocol/2021-May/003550.html
Also these are still part of known failures:
https://gitlab.com/samba-team/samba/-/commit/f5168a21abd029fd57edfd270b86512312c801b1
Hence removing them from this testsuit to remove unnecessary chatter.

smbtorture: remove smb2.replay from the executable tests

---

.gitignore
Makefile
tox.ini

Use tox to run pytest. Use pytest-randomly to have better control on random seed upon re-run due to test failure.

pytest with randomly via tox

---

testcases/mount/mount_io.py
testhelper/testhelper.py

_generate_random_bytes is a private function in mount_io.py. Made it public by adding it to testhelper.py. With this change generate_random_bytes can be reused in any number of tests.
Fixes: #26

testhelper: make _generate_random_bytes public

---

tox.ini

Few minor cleanups to top-level `tox.ini`. Plus, passenv PYTHONPATH.

tox.ini cleanups

---

README.md

README.md: Add details on how the tests are run

---

testcases/smbtorture/test_smbtorture.py

Newer pytest expects test entry-point functions to return None. On CI machines (with CentOS9-stream and Python-3.9) it also yields a warn messages.

smbtorture: return None from test_smbtorture

---

testcases/consistency/test_consistency.py
testcases/mount/test_mount.py
testcases/smbtorture/test_smbtorture.py
testhelper/testhelper.py

pytest by default runs the functions preceeded with test keyword. As a result, all the required test functions will be executed. Hence, this PR simplifies the code by removing the unnecessary main block.

testcases: simplify test structure

---

testcases/mount/test_mount.py

As the seperator('/\') can vary from OS to OS, it is best practice to use os.path.join method instead of string concatination.
This change makes the code platform independent.

Use os.path.join method instead of string concatination

---

testhelper/testhelper.py

Now that we may assume Python-version>=3.9, use standard 'random.randbytes' function to generate semi-random I/O testing data. Improve function's doc string; emphasize that this function is defined to avoid random-pool exhaustion on host machine.

mount: use 'random.randbytes' in _generate_random_bytes

---

testcases/mount/mount_stress.py
testcases/mount/test_mount.py

This test simulates multiple clients performing file operations using the concept of threading.

mount: Add a stress test with multiple clients

---

testcases/containers/images/README.md
testcases/containers/images/smallfile/Containerfile
testcases/containers/images/smallfile/Makefile
testcases/containers/images/smallfile/run_test.sh
testcases/containers/test_containers.py
testcases/containers/test_containers.yml
testcases/tests
testhelper/cmdhelper.py
tox.ini

Adding a smallfiles test which uses podman. 
This will not work at this moment without installing the podman packages and disabling selinux. So setting it to draft for now.

Smallfiles test

---

testcases/smbtorture/selftest/flapping.cephfs

We have identified at least one sub test which we wish to skip the result rather than modifying the server each time for specific use cases. Therefore start with a dedicated flapping file for CephFS.
fixes #35

smbtorture/selftest: Add flapping.cephfs

---

testcases/consistency/test_consistency.py
testcases/containers/test_containers.py
testcases/smbtorture/test_smbtorture.py
testhelper/cmdhelper.py
testhelper/fshelper.py
testhelper/testhelper.py

Several functions are no longer needed after refactoring of some tests.
Also use pathlib.Path so that tests can be used with windows.
depends on #41

Cleanup testhelper and add pathlib.Path to helper functions.

---

testcases/smbtorture/test_smbtorture.py

The current smbtorture tests report output only in case of test failures. This behaviour was a result of the earlier test runner we used.  With pytest we no longer need to worry about managing the output. 
depends on #42

Smbtorture output

---

testcases/containers/images/ltp/Containerfile
testcases/containers/images/ltp/Makefile
testcases/containers/images/ltp/run_ltp.sh
testcases/containers/test_containers.yml

Use well-known open-source LTP[1] test-suits over mounted smb-share, using containerized image. Uses only a subset of tests to check mounted SMB share via podman container. Use also LTP's fsstress utility to tests few cases.
Image URL: `quay.io/samba.org/sit-test-cases:ltp`
[1] https://linux-test-project.github.io/

testcases: containerized subset of LTP test-suits over SMB-share

---

testcases/mount/test_mount_stress.py

With this change we are including one stress test with near maximum values i.e num_clients=20, num_operations=40, file_size=2**25
Other existing tests with lower values are eliminated as the goal here should be to test with maximum stress. Tests with lower values are needless when the test with maximum stress passes.
Fixes: #54

test_mount_stress: include single stress test

---

testcases/mount/conftest.py

Using pamertrize with fixtures in pytest means that the test arguments used no longer use the arguments as the test id. Fix this by converting them using pytest.params() with an id argument.

mount: use pytest.param() on generated parameters

---

testcases/misc/test_dbm.py
testcases/misc/test_io.py
testcases/misc/test_stress.py

Clean up io tests to
a) make the creation and deletion of test subdirectory consistent among tests
b) Run stress test within a sub directory.

Cleanup io

---

testcases/smbtorture/selftest/flapping.cephfs

Many of the tests from `smb2.session` torture suite are already failing on XFS for which _flapping.xfs_ already contains an entry to skip any such failures. With recent update to selftest entries from upstream, compared to _flapping.xfs_ we are left with only one failure(`smb2.session.reauth4`) which needs to be investigated before adding it to the flapping list.

flapping.cephfs: Add specific `smb2.session` tests as knownfail

---

test-info.yml.example

This particular file was incorrectly removed by the patch 
0e09247 (Introduce setup and teardown fixture, 2023-11-22)
Reintroduce this file.

testinfo.yml: reintroduce testinfo.yml.example

---

pyproject.toml

f53d5d3 testcases: mark certain tests as privileged
Introduced the custom mark privileged to mark out tests which need to be run as privileged processes. However this leads to warning messages seen in the warnings summary for the tests.
We register these custom marks to avoid these warning messages.

pyproject.toml: register pytest mark privileged

---

testcases/smbtorture/selftest/flapping.xfs

Most of the tests from _smb2.session_ test suite passes successfully on XFS without any extra setup. Therefore be specific about subtests which are to be ignored due to lack of special and/or proper server setup.

flapping.xfs: Do not consider entire smb2.session as knownfail

---

testcases/smbtorture/smbtorture-tests-info.yml

`smb2.bench-oplock` got renamed to `smb2.bench.oplock` as a separate test within `smb2.bench` test suite. Subsequently more tests got added into `smb2.bench`. Let's remove the old `smb2.bench-oplock` entry and re-add the test suite after checking feasibility of running the independent tests.
Thanks to @spuiuk for pointing out the following smbtorture notice from our test runs:
```
_____________ test_smbtorture[share-xfs-default-smb2.bench-oplock] _____________
----------------------------- Captured stdout call -----------------------------
Command: /bin/smbtorture --fullname --option=torture:progress=no --option=torture:sharedelay=100000 --option=torture:writetimeupdatedelay=500000 --format=subunit --target=samba3 --user=test2%x //192.168.123.10/share-xfs-default …
```

smbtorture: smb2.bench-oplock no longer exists

---

testcases/smbtorture/selftest/flapping.gpfs

Use a dedicated flapping list similar to what we have for XFS to start with filtering GPFS smbtorture test run results.

smbtorture/selftest: Add flapping.gpfs

---

tox.ini

1) The minversion directive used is meant to set minimum tox version and
not the python version to be used. It is hence used incorrectly here.
2) Set the default tox action run to the code checking tools only.

tox: cleanup tox.ini

---

testcases/consistency/test_consistency.py
testhelper/__init__.py
testhelper/cmdhelper.py
testhelper/smbclient.py
tox.ini

This helper class SMBClient provides us with a wrapper around the pysmb module to help replace the smbclient binary.
Unlike PR #74, we use the pysmb module here instead which is a pure python module and is therefore easier to install on our test systems.

testhelper: introduce class SMBClient - pysmb version

---

testcases/smbtorture/selftest/flapping.cephfs
testcases/smbtorture/smbtorture-tests-info.yml

Run the smb2.timestamps test suite in smbtorture.
Fixes #71

testcases/smbtorture: add smb2.timestamps to smbtorture tests

---

testcases/loading/test_loading.py
testhelper/fshelper.py
testhelper/smbclient.py

A simple load test
We use python threads to open up several consecutive connections
on the SMB server and perform either open/write, open/read and delete
operations with an interval of 0-0.5 seconds between each operation.
The tests are run for  fixed duration of time before we stop and
print out the stats for the number of operations performed
This at the moment is a proof of concept of how we can setup a load test. We are still waiting on #74 to be ready before we can use this change. 
The changes proposed are in the last commit. For this code, we set up 100 concurrent connections running for 30 seconds.
depends on #76

Loadtest: Using pysmb to build a load test on a SMB server.

---

testhelper/smbclient.py
tox.ini

pysmb only support SMB2.0 version. The samba-container defaults to using SMB2.1 protocol and we are unable to use pysmb to connect to the samba server. This is a major issue.
The smbprotocol python module avoids this problem.

testhelper/smbclient.py: use smbprotocol python module

---

tox.ini

Output the time required to setup, call and teardown each test. We only report times which take longer than 0.05 seconds.
This information can be used to compare performance against differing setups.

tox: list the time taken to run each test

---

testcases/smbtorture/selftest/flapping.cephfs-vfs

With certain samba configurations we might require a separate flapping list for variants of a backend. One such situation is detailed in https://github.com/samba-in-kubernetes/sit-environment/pull/109 where specific test run results differ among variants of a particular backend.

selftest: Add a dedicated flapping list for CephFS vfs

---

testcases/smbtorture/selftest/flapping.cephfs
testcases/smbtorture/selftest/flapping.xfs

With recent changes to _[smb.conf](https://github.com/samba-in-kubernetes/sit-environment/pull/109)_, _smb2.session.reauth4_ is expected to fail on XFS and CephFS kclient method. You can find more details from https://github.com/samba-in-kubernetes/sit-environment/pull/109#issuecomment-2208737127.
Also remember that this is **_not a problem with CephFS vfs_** approach but our clone of selftest mechanism currently lacks the ability to consider flapping lists based on variants for a particular backend.

Add smb2.session.reauth4 to flapping list for XFS and CephFS(kclient)

---

test-info.yml.example
testcases/smbtorture/test_smbtorture.py

This helps us tailor tests for cases where the behaviour changes according to the filesystem variant being used.
In this case, we use it with the smbtorture tests where we select the flapping list for the filesystem-variant and it it doesn't exist, fall back to filesystem file.

test-info.yml: add filesystem variant to the backend

---

testcases/smbtorture/selftest/flapping.cephfs

_smb2.charset_ contains a composite character test attempting to create accented character which could fail on case insensitive CephFS subvolumes. Therefore add the corresponding test to the flapping list for CephFS.
> smbtorture 4.24.0pre1-UNKNOWN
> Using seed 1756437765
> time: 2025-08-29 03:22:45.742934Z
> progress: 4
> test: samba3.smb2.charset.Testing composite character (a umlaut)
> time: 2025-08-29 03:22:45.743692Z
> time: 2025-08-29 03:22:45.894823Z
> **failure**: samba3.smb2.charset.Testing composite character (a umlaut) [
> Exception: ../../source4/torture/smb2/charset.c:119: status was NT_STATUS_OBJECT_NAME_COLLISION, expected NT_STATUS_OK: Failed to create accented character
> 
> ]

smbtorture: Add accented character test to flapping.cephfs

---

testcases/smbtorture/selftest/flapping.cephfs

_smb2.timestamps.modern_write_time_update-1_ does not run successfully on non-proxy enabled CephFS shares due to an underlying bug which is reported via tracker [#71622](https://tracker.ceph.com/issues/71622). For now we add it to the flapping list until the issue is fixed.

smbtorture: Add `modern_write_time_update-1` test to flapping.cephfs
